#!/bin/sh
#
# sync mingw packages from obs to a remote site
#
# SPDX-FileCopyrightText: 2022 Ralf Habacker <ralf.habacker@freenet.de>
# SPDX-License-Identifier: MIT
#

r=$(realpath $0)
r=$(dirname $r)
r=$(dirname $r)
bn=$(basename $0)


# Make sure the temp directory gets removed on script exit.
trap "exit 1"           HUP INT PIPE QUIT TERM
trap 'rm -rf "$TEMPD"'  EXIT

run=
clean=0

for arg in "$@"
do
    case "$arg" in
        --dry-run)
            run=echo
            shift
            ;;
    esac
done

if test -n "$1"; then
    confs=$1
else
    confs=$(find $r/conf/*.conf)
fi

# Create a temporary directory and store its name in a variable.
TEMPD=$(mktemp -d)

# Exit if the temp directory wasn't created successfully.
if [ ! -e "$TEMPD" ]; then
    >&2 echo "Failed to create temp directory"
    exit 1
fi

cd $TEMPD

for i in $confs; do
    . $i
    # clean dir
    rm -rf *
    # set options
    if test -n "$multibuild"; then
        m="--multibuild-package=$multibuild"
    fi
    # fetch packages
    $run osc getbinaries -d $(pwd) $m $project $package $repo x86_64
    # unpack
    for i in $(find -name '*.rpm'); do
        $run rpm2cpio $i |  cpio -idmv
    done
    # upload packages
    $run scp *.7z *.exe $user@$host:$path
done
